name: Maven CI with Allure

on:
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: "Allure TestOps service parameter. Leave blank."
        required: false
      ALLURE_USERNAME:
        description: "Allure TestOps service parameter. Leave blank."
        required: false

env:
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Set up AllureCTL
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: https://demo.testops.cloud
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: 4601

      - name: Run tests with Maven under AllureCTL
        run: allurectl watch -- mvn clean test
        env:
          ALLURE_RESULTS: target/allure-results
